name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: windows-latest
    
    env:
      LISP: sbcl-bin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # This single step sets up Roswell AND installs SBCL
      - name: Setup Common Lisp
        uses: 40ants/setup-lisp@v4
        with:
          asdf-system: cl-win32-types

      - name: Install Dependencies & Run Tests
        shell: lispsh -eo pipefail {0}
        run: |
          ros install fiveam
          ros --eval "(asdf:test-system :cl-win32-types)" --quit